#!/bin/sh
##
##  Copyright 2004 The Apache Software Foundation
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##

if [ -z "$XMLBEANS_HOME" ]; then
    XMLBEANS_HOME=`dirname $0`/..
fi

XMLBEANS_LIB=
if ls $XMLBEANS_HOME/build/lib/xmlbeans*.jar 1> /dev/null 2>&1; then
    XMLBEANS_LIB=$XMLBEANS_HOME/build/lib
fi
if ls $XMLBEANS_HOME/lib/xmlbeans*.jar 1> /dev/null 2>&1; then
    XMLBEANS_LIB=$XMLBEANS_HOME/lib
fi

echo XMLBEANS_LIB=$XMLBEANS_LIB

if [ -z "$XMLBEANS_LIB" ]; then
    echo "ERROR: Could not find xmlbeans*.jar, try set XMLBEANS_LIB to the directory containing xmlbeans*.jar"
fi
